POST http://localhost:3004/api/notes
content-type: application/json

{
   "content":"Postman is good in testing backend",
   "important":true 
}
###
POST http://localhost:3001/api/notes
content-type: application/json

{
   "content":"Morgan",
   "important":true 
}
###
POST http://localhost:3001/api/notes
content-type: application/json

{
   "content":"MongoDB + mongoose",
   "important":true 
}
###
POST http://localhost:3001/api/notes
content-type: application/json

{
   "content":"Hello, World!",
   "important":true 
}